name: 'ECS Build and Deploy'
description: 'ECS Build and Deploy Github Action'
inputs:
  build_path:  # id of input
    description: 'Working directory for build'
    required: true
    default: '/'
  aws_secret_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_key:
    description: 'AWS Secret Access Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_secret_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Login to Amazon CodeArtifact
      id: login-codeartifact
      working-directory: ${{ inputs.build_path }}
      run: aws codeartifact login --tool npm --repository onkai-npm-packages --domain onkai --namespace onkai --duration-seconds 900

    - name: Copy npmrc
      working-directory: ${{ inputs.build_path }}
      run: cat /root/.npmrc && cp /root/.npmrc ./npmrc 

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ecr_repository }}
        BRANCH: ${{ env.branch }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH .${{ inputs.build_path }}
        docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG"